name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  message:  # id of input
    description: 'Imput parameter'
    required: true
    # default: '--- Default Message in the action ---'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'